class_name: youtube_dataset # class name of the dataset
disp_name: youtube_demo_5-frame # display name of the dataset, used for logging
dir: demo/MEF
csv_dir: data_split/demo/MEF # csv directory
num_frames: 5 # number of frames to sample
frame_gap_ls: [0] # frame gap between the first and second frames
stride: 1 # stride for sampling frames
frame_padding: true  # if true, repeat the first and last frames for padding